<?php
/**
 * Heb customer data custom form
 *
 * @see Heb_Customerform_Block_Account_Form
 */
?>
<?php if($this->getTitle()): ?>
<div class="page-title">
    <h1><?php echo $this->getTitle() ?></h1>
</div>
<?php endif; ?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="form-validate" autocomplete="off">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__('Formulario') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <?php echo $this->getLayout()->createBlock('customerform/widget_name')->setObject($this->getCustomer())->toHtml() ?>
            </li>
            <?php $_dob = $this->getLayout()->createBlock('customerform/widget_dob') ?>
            <li><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></li>
            <li>
                <label for="email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
                <div class="input-box">
                    <input type="text" name="email" id="email" value="<?php echo $this->escapeHtml($this->getEmail()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" class="input-text required-entry validate-email" />
                </div>
            </li>
            <li>
                <label for="email-confirmation" class="required"><em>*</em><?php echo $this->__('Confirmar Email') ?></label>
                <div class="input-box">
                    <input type="text" name="email-confirmation" id="email-confirmation" value="" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address Confirmation')) ?>" class="input-text required-entry validate-email" />
                </div>
            </li>
            <li>                
                <label for="phone" class="required"><em>*</em><?php echo $this->__('Teléfono (máx. 10 dígitos)') ?></label>
                <div class="input-box">
                    <input type="text" name="phone" value="<?php echo $this->escapeHtml($this->getPhone()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" class="input-text  <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?> validate-digits" id="phone" maxlength="10"/>
                </div>                              
            </li>           
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Campos Requeridos') ?></p>
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save')) ?>" class="button"><span><span><?php echo $this->__('Enviar') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
